### PR TITLE
bump aiida-core to 1.6.5

### PR DESCRIPTION
**Pull request by ltalirz**
and python to 3.8

### CODE REVIEW

**Comment by ltalirz** [comment]
@chrisjsewell 
rabbitmq doesn't want to start on centos. weird...

**Comment by chrisjsewell** [comment]
CENTOS is dead anyway: https://thenewstack.io/red-hat-deprecates-linux-centos-in-favor-of-a-streaming-edition/, so I wouldn't be against entirely removing that test

**Comment by ltalirz** [comment]
Yeah... @espenfl open to switching to rocky linux? ;-)

In the other OSs it's down to idempotence issues
```
2021-09-24T08:42:38.7184206Z ERROR: Idempotence test failed because of the following tasks:
2021-09-24T08:42:38.7186701Z * [instance] => marvel-nccr.python : create virtual environment: ${HOME}/.virtualenvs/aiida
2021-09-24T08:42:38.7188561Z * [instance] => marvel-nccr.aiida : Install aiida-core + plugins into venv
2021-09-24T08:42:38.7190286Z * [instance] => marvel-nccr.aiida : Install aiida-core from GitHub (editable)
2021-09-24T08:42:38.7192012Z * [instance] => marvel-nccr.aiida : Install aiida-core from GitHub (editable)
```

**Comment by chrisjsewell** [comment]
> Yeah... @espenfl open to switching to rocky linux? ;-)

Stupid Linux and their multiple distros (Linus hates it: https://youtu.be/Pzl1B7nB9Kc)
Yeh thats by the original centos creator isn't it.
Well there is a docker image for it: https://github.com/geerlingguy/docker-rockylinux8-ansible, so shouldn't be too hard to add

**Comment by ltalirz** [comment]
@chrisjsewell the idempotency issue remains. do you have an idea what might be causing it?

Somehow, already when running the `create virtual environment: ${HOME}/.virtualenvs/aiida` task the second time this must result in changes. It don't think it's the `aiida_install_packages` but I also don't quite know what else it could be...

**Comment by chrisjsewell** [comment]
Yeh maybe a change in ipykernel version? Can you get debug info of e.g. pip freeze before/after installing aiida-core ?

**Comment by ltalirz** [comment]
the version of the ipykernel dependency in the `aiida_install_packages` is not locked down, so I wonder a bit how this could be an issue...

I think this would be best debugged by trying it locally; I'll see whether I get round to it

**Comment by ltalirz** [comment]
I'm not able to get the vbox image to start on my MacOs; the error is the one here: https://stackoverflow.com/questions/64852413/big-sur-macos-vagrant-issue

Already tried updating to latest vagrant + vbox version + playing around with privacy settings.
Will need to stop here for the moment

**Comment by ltalirz** [comment]
@chrisjsewell would you be able at having a quick shot to run this locally (i.e. building QM barebones + run the AiiDA role twice?)?

**Comment by ltalirz** [comment]
Closing this outdated PR

**Pull request closed without merging**
