### PR TITLE
update plugins

### PR DESCRIPTION
**Pull request by ltalirz**
* re-add aiida-yambo
 * re-add aiida-wannier90
 * enable testing of plugin installation
 * fix owner of aiida template/data folders

### CODE REVIEW

**Comment by ltalirz** [comment]
@espenfl (only) the tests on centos fail, seemingly while building the C extensions for pymatgen.

To me, there seem to be not one but two issues:
 1. The error occurs when installing aiida-quantumespresso. Before this, we already install aiida-core with the `atomic_tools` extra, which includes pymatgen. I.e. pymatgen should already be present at that point.
 2. The actual build error. From what I can see it is `trying to exec 'cc1plus': execvp: No such file or directory`

Would you mind looking into what is going on there?

**Comment by espenfl** [comment]
@ltalirz Okey. Seems there is now some `c++` dependent stuff in `pymatgen` as we did not have this problem before. Please add `gcc-c++` to `aiida-deps-rhel.yml` which should solve the second problem.

For the first one, I am not really sure. And it seems a bit strange. You can see from the output that `Collecting pymatgen>=2019.7.2\n  Downloading pymatgen-2020.3.2.tar.gz`. The collect is corrected based on the `setup.json` for recent core. To me that looks strange. Tried to see if there were other deps that require `2020.3.2` (which is currently the most recent, so might be something without pinning) but seems the `aiida-quantumespresso` does not use `pymatgen`.

**Comment by espenfl** [comment]
@ltalirz Aha, we only do `"aiida-core[rest]"` so if we want `atomic_tools` we should add that as well. So that explains why we get the `pymatgen` error at `aiida-quantumespresso` which requires `atomic_tools`. However, why it pulls down a newer version is a bit beyond me. But I have not checked in detail.

**Comment by ltalirz** [comment]
@espenfl Thanks a lot for looking into this, much appreciated!

> Aha, we only do "aiida-core[rest]" so if we want atomic_tools we should add that as well.

Thanks - I just saw the `aiida_extras` variable and thought we were using it - turns out we've been ignoring it ;-)

>  Please add gcc-c++ to aiida-deps-rhel.yml

Great, will do!

**Pull request merged**
